import type { CkanPackage, DiscoveredResource, SourceRegistryEntry } from "./types.ts";
import { discoverResources } from "./resource-discovery.ts";

const reviewDate = "2026-08-24T00:00:00.000Z";
const nhsbsaApi = "https://opendata.nhsbsa.net/api/3/action";

function nhsbsa(
  sourceId: string,
  datasetName: string,
  slug: string,
  purpose: string,
  caveats: readonly string[] = [],
): SourceRegistryEntry {
  return Object.freeze({
    sourceId,
    publisher: "NHS Business Services Authority",
    datasetName,
    datasetSlugOrIdentifier: slug,
    jurisdiction: "England",
    coverage: "England; source-specific exclusions and reporting definitions apply",
    purpose,
    accessMethod: "ckan_action_api",
    apiOrDownload: nhsbsaApi,
    baseEndpointOrDiscoveryMethod: `package_show resolved from current package_search results for ${slug}`,
    licence: "Open Government Licence v3.0",
    publicationFrequency: "Source metadata determines cadence",
    typicalReportingLag: "Source metadata determines lag",
    latestExpectedPeriod: null,
    latestDiscoveredPeriod: null,
    latestResourceId: null,
    resourceUrl: null,
    resourceHashOrChecksum: null,
    schemaVersion: null,
    schemaFingerprint: null,
    firstSeenAt: reviewDate,
    lastCheckedAt: null,
    lastSuccessfullyIngestedAt: null,
    authorityRank: 1,
    status: "discovery_implemented",
    knownCaveats: Object.freeze([...caveats]),
    provenanceNotes: "The package identifier is verified through the publisher's live CKAN Action API; monthly resource UUIDs are never hard-coded into ingestion jobs.",
  });
}

export const sourceRegistry = Object.freeze([
  nhsbsa("nhsbsa.epd", "English Prescribing Dataset (EPD) with SNOMED Code", "english-prescribing-dataset-epd-with-snomed-code", "Practice-level prescribing activity and cost facts.", ["Practice postcode is an organisation address, not patient residence.", "Prescribed activity is not the same as dispensing or NovaPharm sales."]),
  nhsbsa("nhsbsa.pca", "Prescription Cost Analysis (PCA) Monthly Administrative Data", "prescription-cost-analysis-pca-monthly-data", "Community dispensing and reimbursement-oriented market totals.", ["Management information, not an official statistic.", "PCA and EPD measure different stages and must not be naively summed."]),
  nhsbsa("nhsbsa.bnf-current", "BNF Code Information - Current Year", "bnf-code-information-current-year", "Current BNF hierarchy and presentation identity."),
  nhsbsa("nhsbsa.bnf-historic", "BNF Code Information - Historic", "bnf-code-information-historic", "Historic BNF hierarchy and temporal identity."),
  nhsbsa("nhsbsa.bnf-changes", "BNF Code Information - Monthly Changes", "bnf-code-information-monthly-changes", "BNF change detection and temporal mapping."),
  nhsbsa("nhsbsa.prescriber-details", "Prescriber Details", "prescriber-details", "Prescriber and practice master enrichment."),
  nhsbsa("nhsbsa.hospital-community", "Hospital Prescribing Dispensed in the Community", "hospital-prescribing-dispensed-in-the-community", "Hospital-origin prescribing dispensed in the community.", ["This source is distinct from both EPD and secondary-care issues."]),
  nhsbsa("nhsbsa.scmd-provisional", "Provisional Secondary Care Medicines Data with indicative price", "secondary-care-medicines-data-indicative-price", "Provisional trust-level secondary-care medicine issues.", ["Indicative cost is not actual hospital acquisition cost.", "The July 2026 schema change requires version-aware identifier and unit handling."]),
  nhsbsa("nhsbsa.scmd-final", "Finalised Secondary Care Medicines Data with indicative price", "finalised-secondary-care-medicines-data-scmd-with-indicative-price", "Finalised trust-level secondary-care medicine issues.", ["Indicative cost is not actual hospital acquisition cost."]),
  nhsbsa("nhsbsa.contractor-details", "Contractor Details", "contractor-details", "England dispensing-contractor identity and address master."),
  nhsbsa("nhsbsa.pharmacy-activity", "Pharmacy and appliance contractor dispensing data", "pharmacy-and-appliance-contractor-dispensing-data", "Contractor activity and service signals.", ["This is not a complete medicine-by-pharmacy-by-month fact feed."]),
  nhsbsa("nhsbsa.practice-dispensing", "Dispensing Practices dispensing data", "dispensing-practices-dispensing-data", "Practice-to-dispensing-contractor flow and item counts."),
  nhsbsa("nhsbsa.padm", "Dispensing doctor and personally administered dispensing data", "dispensing-doctor-and-personally-administered-padm-dispensing-data", "Special dispenser and personally administered activity."),
  nhsbsa("nhsbsa.pharmacy-open-close", "Pharmacy Openings and Closures", "pharmacy-openings-and-closures", "National pharmacy estate movement aggregates.", ["This aggregate source does not identify individual premises changes."]),
  nhsbsa("nhsbsa.consolidated-pharmacy", "Consolidated Pharmaceutical List", "consolidated-pharmaceutical-list", "England pharmacy premise, ownership and opening-hours cross-check."),
  Object.freeze({
    sourceId: "nhsbsa.bnf-snomed-map", publisher: "NHS Business Services Authority", datasetName: "BNF / SNOMED mapping", datasetSlugOrIdentifier: "bnf-snomed-mapping", jurisdiction: "England", coverage: "All published VMP, AMP, VMPP and AMPP mappings for the release", purpose: "Temporal BNF-to-SNOMED medicine identity mapping.", accessMethod: "file_download", apiOrDownload: "https://www.nhsbsa.nhs.uk/prescription-data/understanding-our-data/bnf-snomed-mapping", baseEndpointOrDiscoveryMethod: "Publisher release page; migration to CKAN announced for September 2026", licence: "Publisher terms and Open Government Licence where stated", publicationFrequency: "Monthly", typicalReportingLag: "Approximately two months", latestDiscoveredPeriod: null, latestResourceId: null, resourceUrl: null, resourceHashOrChecksum: null, schemaVersion: null, schemaFingerprint: null, firstSeenAt: reviewDate, lastCheckedAt: null, lastSuccessfullyIngestedAt: null, authorityRank: 1, status: "documented_adapter_pending", knownCaveats: Object.freeze(["Current delivery is a ZIP containing an Excel workbook.", "Historic mapping corrections and code changes must be retained."]), provenanceNotes: "NHSBSA announced a phased move to its Open Data Portal; discovery must change only after the new source is verified." }),
  Object.freeze({
    sourceId: "nhse.dmd", publisher: "NHS England and NHS Business Services Authority", datasetName: "NHS dictionary of medicines and devices (dm+d)", datasetSlugOrIdentifier: "SCCI0052", jurisdiction: "United Kingdom", coverage: "NHS medicine and device terminology; release scope applies", purpose: "Canonical VTM, VMP, AMP, VMPP and AMPP identity and history.", accessMethod: "fhir_api", apiOrDownload: "https://digital.nhs.uk/developer/api-catalogue/terminology-server-fhir", baseEndpointOrDiscoveryMethod: "NHS England Terminology Server or licensed TRUD release", licence: "Open Government Licence; TRUD account and licence acceptance required for raw release files", publicationFrequency: "Weekly", typicalReportingLag: "Publisher release schedule", latestDiscoveredPeriod: null, latestResourceId: null, resourceUrl: null, resourceHashOrChecksum: null, schemaVersion: null, schemaFingerprint: null, firstSeenAt: reviewDate, lastCheckedAt: null, lastSuccessfullyIngestedAt: null, authorityRank: 1, status: "credentials_required", knownCaveats: Object.freeze(["Terminology Server onboarding or TRUD access is required.", "dm+d and SNOMED UK Drug Extension timing can differ."]), provenanceNotes: "No production terminology credentials are present in the repository." }),
  Object.freeze({
    sourceId: "nhse.ods-fhir-r4", publisher: "NHS England", datasetName: "Organisation Data Terminology FHIR R4", datasetSlugOrIdentifier: "organisation-data-terminology", jurisdiction: "England", coverage: "NHS organisations, relationships, status and geography", purpose: "Current and historic organisation identity, succession and relationships.", accessMethod: "fhir_api", apiOrDownload: "https://api.service.nhs.uk/organisation-data-terminology-api/fhir", baseEndpointOrDiscoveryMethod: "https://digital.nhs.uk/developer/api-catalogue/organisation-data-terminology", licence: "NHS England API terms", publicationFrequency: "Daily", typicalReportingLag: "Operational update cycle", latestDiscoveredPeriod: null, latestResourceId: null, resourceUrl: null, resourceHashOrChecksum: null, schemaVersion: "FHIR 4.0.1", schemaFingerprint: null, firstSeenAt: reviewDate, lastCheckedAt: reviewDate, lastSuccessfullyIngestedAt: null, authorityRank: 1, status: "credentials_required", knownCaveats: Object.freeze(["Production and integration access require NHS API onboarding and a server-side API key.", "Historic relationships must be applied as-of the analytical month."]), provenanceNotes: "A bounded FHIR R4 client is implemented and sandbox-testable. Production remains configuration-required; the retired STU3 interface is not used." }),
  Object.freeze({
    sourceId: "nhse.dohs-v3", publisher: "NHS England", datasetName: "Directory of Healthcare Services API", datasetSlugOrIdentifier: "dohs-v3", jurisdiction: "England", coverage: "Public healthcare service and contact information", purpose: "Pharmacy service and defensible public contact enrichment.", accessMethod: "rest_api", apiOrDownload: "https://api.service.nhs.uk/service-search-api", baseEndpointOrDiscoveryMethod: "https://digital.nhs.uk/developer/api-catalogue/directory-of-healthcare-services/version-3", licence: "NHS England API terms", publicationFrequency: "Operational", typicalReportingLag: "Source dependent", latestDiscoveredPeriod: null, latestResourceId: null, resourceUrl: null, resourceHashOrChecksum: null, schemaVersion: "v3", schemaFingerprint: null, firstSeenAt: reviewDate, lastCheckedAt: reviewDate, lastSuccessfullyIngestedAt: null, authorityRank: 1, status: "credentials_required", knownCaveats: Object.freeze(["Production and integration access require NHS API onboarding and a server-side API key.", "A listed contact is not automatically the preferred non-NHS commercial email."]), provenanceNotes: "A bounded DoHS v3 REST client is implemented with ODS-code lookup and server-only API-key authentication. Production remains configuration-required." }),
  Object.freeze({
    sourceId: "nhse.registered-patients", publisher: "NHS England", datasetName: "Patients Registered at a GP Practice", datasetSlugOrIdentifier: "patients-registered-at-a-gp-practice", jurisdiction: "England", coverage: "GP practices, sub-ICB locations, ICBs, commissioning regions and England", purpose: "Monthly practice registered-population denominators, five-year age and sex bands, and contemporaneous practice-to-NHS-organisation mapping.", accessMethod: "file_download", apiOrDownload: "https://digital.nhs.uk/data-and-information/publications/statistical/patients-registered-at-a-gp-practice", baseEndpointOrDiscoveryMethod: "Latest monthly publication page and its all-practice, five-year-age and mapping resources", licence: "Open Government Licence v3.0", publicationFrequency: "Monthly", typicalReportingLag: "Approximately two weeks after the monthly snapshot", latestExpectedPeriod: "2026-08", latestDiscoveredPeriod: "2026-08", latestResourceId: "gp-reg-pat-prac-all", resourceUrl: "https://files.digital.nhs.uk/45/E255E0/gp-reg-pat-prac-all.zip", resourceHashOrChecksum: "sha256:0cd043122841f36107323d8ad8d4a50415024f52589218a47d5753de8bcaf7c0", schemaVersion: "2026-08/all+quin-age+map", schemaFingerprint: null, firstSeenAt: reviewDate, lastCheckedAt: reviewDate, lastSuccessfullyIngestedAt: null, authorityRank: 1, status: "discovery_implemented", knownCaveats: Object.freeze(["Registered population is a practice-list denominator, not patient residence.", "Monthly mapping must be applied as-of the publication month rather than replaced with today's organisation structure.", "Only aggregate counts are permitted; no patient-level data is required or retained."]), provenanceNotes: "August 2026 was published on 13 August 2026 from a 1 August snapshot. The importer, exact schema contracts and repository evidence validate all three resources in an isolated local database; this static registry seed does not claim production ingestion, whose state comes from the ingestion-run ledger." }),
  Object.freeze({
    sourceId: "nhse.qof", publisher: "NHS England", datasetName: "Quality and Outcomes Framework", datasetSlugOrIdentifier: "quality-and-outcomes-framework-achievement-prevalence-and-exceptions-data", jurisdiction: "England", coverage: "Participating GP practices, sub-ICB locations, ICBs, regions and England", purpose: "Governed disease-prevalence context for clinically defensible therapeutic-area modelling.", accessMethod: "file_download", apiOrDownload: "https://digital.nhs.uk/data-and-information/publications/statistical/quality-and-outcomes-framework-achievement-prevalence-and-exceptions-data", baseEndpointOrDiscoveryMethod: "Latest published annual QOF release and raw CSV resource", licence: "Open Government Licence v3.0", publicationFrequency: "Annual", typicalReportingLag: "Approximately five months after the reporting year", latestExpectedPeriod: "2024-25", latestDiscoveredPeriod: "2024-25", latestResourceId: null, resourceUrl: null, resourceHashOrChecksum: null, schemaVersion: "2024-25", schemaFingerprint: null, firstSeenAt: reviewDate, lastCheckedAt: reviewDate, lastSuccessfullyIngestedAt: null, authorityRank: 1, status: "documented_adapter_pending", knownCaveats: Object.freeze(["QOF participation is voluntary and coverage is not universal.", "Practice mappings in the 2024-25 release use reference data current on 1 April 2025.", "Prevalence can be used only for clinically defensible context and never as patient-level diagnosis or proof of causation."]), provenanceNotes: "The latest complete release at review is 2024-25, published 28 August 2025. The 2025-26 release was scheduled for 27 August 2026 and was not treated as available early." }),
  Object.freeze({
    sourceId: "ons.small-area-population", publisher: "Office for National Statistics", datasetName: "Lower layer Super Output Area population estimates (Accredited official statistics)", datasetSlugOrIdentifier: "lower-layer-super-output-area-population-estimates", jurisdiction: "United Kingdom", coverage: "LSOAs in England and Wales by broad age group and sex", purpose: "Official small-area demographic context for geography and forecasting features.", accessMethod: "file_download", apiOrDownload: "https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/lowersuperoutputareamidyearpopulationestimatesnationalstatistics", baseEndpointOrDiscoveryMethod: "Current ONS dataset edition page", licence: "Open Government Licence v3.0", publicationFrequency: "Annual", typicalReportingLag: "Publisher release cycle", latestExpectedPeriod: "2024", latestDiscoveredPeriod: "2024", latestResourceId: null, resourceUrl: null, resourceHashOrChecksum: null, schemaVersion: "mid-2022-revised-to-mid-2024", schemaFingerprint: null, firstSeenAt: reviewDate, lastCheckedAt: reviewDate, lastSuccessfullyIngestedAt: null, authorityRank: 1, status: "documented_adapter_pending", knownCaveats: Object.freeze(["Coverage is England and Wales, not all UK nations.", "The estimates describe usual residence and must not be confused with GP registered populations.", "Historic estimates may be revised between editions."]), provenanceNotes: "The latest identified edition was released 7 November 2025 and contains revised mid-2022 through mid-2024 estimates." }),
  Object.freeze({
    sourceId: "mhclg.imd2025", publisher: "Ministry of Housing, Communities and Local Government", datasetName: "English indices of deprivation 2025 - File 7", datasetSlugOrIdentifier: "english-indices-of-deprivation-2025-file-7", jurisdiction: "England", coverage: "33,755 Census 2021 LSOAs in England", purpose: "LSOA-level deprivation ranks and deciles for contextual analysis and territory interpretation.", accessMethod: "file_download", apiOrDownload: "https://www.gov.uk/government/statistics/english-indices-of-deprivation-2025", baseEndpointOrDiscoveryMethod: "Official release page; use the corrected v2 File 7 CSV", licence: "Open Government Licence v3.0", publicationFrequency: "Irregular official release cycle", typicalReportingLag: "Not a monthly operational source", latestExpectedPeriod: "2025", latestDiscoveredPeriod: "2025", latestResourceId: "file-7-v2", resourceUrl: "https://assets.publishing.service.gov.uk/media/691ded56d140bbbaa59a2a7d/File_7_IoD2025_All_Ranks_Scores_Deciles_Population_Denominators.csv", resourceHashOrChecksum: null, schemaVersion: "IoD25-v2", schemaFingerprint: null, firstSeenAt: reviewDate, lastCheckedAt: reviewDate, lastSuccessfullyIngestedAt: null, authorityRank: 1, status: "documented_adapter_pending", knownCaveats: Object.freeze(["The indices measure relative deprivation and are not direct measures of individual circumstances.", "Only England is covered.", "Ranks and deciles are preferred to casual interpretation of scores."]), provenanceNotes: "The release was updated on 17 November 2025 after corrected ONS geography allocation; only the corrected v2 files are acceptable." }),
  Object.freeze({
    sourceId: "ons.rural-urban-2021", publisher: "Office for National Statistics", datasetName: "2021 Rural Urban Classification", datasetSlugOrIdentifier: "2021-rural-urban-classification", jurisdiction: "United Kingdom", coverage: "Census 2021 statistical geographies in England and Wales", purpose: "Official rural/urban context for geography and territory interpretation.", accessMethod: "file_download", apiOrDownload: "https://www.ons.gov.uk/methodology/geography/geographicalproducts/ruralurbanclassifications/2021ruralurbanclassification", baseEndpointOrDiscoveryMethod: "Official ONS classification page and linked OA, LSOA, MSOA and LAD products", licence: "Open Government Licence v3.0", publicationFrequency: "Census classification cycle with publisher updates", typicalReportingLag: "Not an operational monthly source", latestExpectedPeriod: "2021", latestDiscoveredPeriod: "2021", latestResourceId: null, resourceUrl: null, resourceHashOrChecksum: null, schemaVersion: "RUC21", schemaFingerprint: null, firstSeenAt: reviewDate, lastCheckedAt: reviewDate, lastSuccessfullyIngestedAt: null, authorityRank: 1, status: "documented_adapter_pending", knownCaveats: Object.freeze(["Coverage is England and Wales; other nations require their own official classifications.", "Rurality is area context and must not be treated as an attribute of an individual."]), provenanceNotes: "Output Areas are the base classification; higher-level classifications must use the official ONS derivation or lookup rather than ad hoc thresholds." }),
  Object.freeze({
    sourceId: "ons.onspd-live", publisher: "Office for National Statistics", datasetName: "Online ONS Postcode Directory (Live)", datasetSlugOrIdentifier: "2ced9a3a2462432a92c31226e3cd3aa5", jurisdiction: "United Kingdom", coverage: "Current UK postcodes with statistical and administrative geography", purpose: "Authoritative current-postcode coordinates and geography mapping.", accessMethod: "arcgis_feature_service", apiOrDownload: "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/Online_ONS_Postcode_Directory_Live/FeatureServer/1", baseEndpointOrDiscoveryMethod: "Official ONS Open Geography Portal ArcGIS item owned by ONSGeography_data", licence: "Open Government Licence v3.0 with source attribution requirements", publicationFrequency: "Live service; downloadable products quarterly", typicalReportingLag: "Publisher update cycle", latestDiscoveredPeriod: null, latestResourceId: "2ced9a3a2462432a92c31226e3cd3aa5", resourceUrl: "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/Online_ONS_Postcode_Directory_Live/FeatureServer/1", resourceHashOrChecksum: null, schemaVersion: "live-2026", schemaFingerprint: null, firstSeenAt: reviewDate, lastCheckedAt: reviewDate, lastSuccessfullyIngestedAt: null, authorityRank: 1, status: "discovery_implemented", knownCaveats: Object.freeze(["Postcode centroids are approximate locations, not premises coordinates.", "The live layer omits some terminated postcodes; the governed quarterly ONSPD fallback preserves historic records."]), provenanceNotes: "The current layer exposes PCDS, introduction/termination dates, latitude, longitude, ICB, LSOA, MSOA and rurality fields." }),
  Object.freeze({
    sourceId: "ons.onspd-quarterly", publisher: "Office for National Statistics", datasetName: "ONS Postcode Directory (May 2026) for the United Kingdom", datasetSlugOrIdentifier: "d1317f804688417287de8f8224ecc942", jurisdiction: "United Kingdom", coverage: "Current and terminated UK postcodes in the May 2026 quarterly ONSPD release", purpose: "Temporal fallback for postcodes omitted from the current-only live centroid layer.", accessMethod: "arcgis_feature_service", apiOrDownload: "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/ONS_Postcode_Directory_(May_2026)_for_the_United_Kingdom_(Hosted_Table)/FeatureServer/0", baseEndpointOrDiscoveryMethod: "Official ONS Open Geography Portal owner search for the latest quarterly hosted ONSPD table", licence: "Open Government Licence v3.0 with source attribution requirements", publicationFrequency: "Quarterly", typicalReportingLag: "Publisher update cycle", latestDiscoveredPeriod: "2026-05", latestResourceId: "d1317f804688417287de8f8224ecc942", resourceUrl: "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/ONS_Postcode_Directory_(May_2026)_for_the_United_Kingdom_(Hosted_Table)/FeatureServer/0", resourceHashOrChecksum: null, schemaVersion: "2026-05", schemaFingerprint: null, firstSeenAt: reviewDate, lastCheckedAt: reviewDate, lastSuccessfullyIngestedAt: null, authorityRank: 1, status: "discovery_implemented", knownCaveats: Object.freeze(["The quarterly snapshot can lag the live service.", "Terminated postcodes are retained for temporal evidence and must not be presented as current addresses."]), provenanceNotes: "This source is queried only after the live layer has no current match; the quarterly release preserves terminated postcode centroids." }),
  Object.freeze({
    sourceId: "phs.prescribed-dispensed", publisher: "Public Health Scotland", datasetName: "Prescribed and Dispensed", datasetSlugOrIdentifier: "prescribed-dispensed", jurisdiction: "Scotland", coverage: "Community prescribing and dispensing in Scotland", purpose: "Prescriber-to-dispenser item flow and Scottish pharmacy geography.", accessMethod: "ckan_action_api", apiOrDownload: "https://www.opendata.nhs.scot/api/3/action", baseEndpointOrDiscoveryMethod: "package_show for prescribed-dispensed", licence: "Open Government Licence v3.0", publicationFrequency: "Quarterly", typicalReportingLag: "Two to three months", latestDiscoveredPeriod: null, latestResourceId: null, resourceUrl: null, resourceHashOrChecksum: null, schemaVersion: null, schemaFingerprint: null, firstSeenAt: reviewDate, lastCheckedAt: null, lastSuccessfullyIngestedAt: null, authorityRank: 1, status: "discovery_implemented", knownCaveats: Object.freeze(["Data from May 2023 onward is provisional and may not be directly comparable with earlier data.", "Prescribed and dispensed identities remain distinct."]), provenanceNotes: "Official PHS source covering prescriber and dispenser locations." }),
  Object.freeze({
    sourceId: "nwssp.pharmacies", publisher: "NHS Wales Shared Services Partnership", datasetName: "Pharmacies in Wales", datasetSlugOrIdentifier: "pharmacies-in-wales", jurisdiction: "Wales", coverage: "Open pharmacies in Wales reported to Primary Care Services", purpose: "Wales pharmacy premise and ownership cross-check.", accessMethod: "file_download", apiOrDownload: "https://nwssp.nhs.wales/ourservices/primary-care-services/general-information/data-and-publications/pharmacies-in-wales/", baseEndpointOrDiscoveryMethod: "Publisher page and linked quarterly file", licence: "NHS Wales publication terms", publicationFrequency: "Quarterly", typicalReportingLag: "Publisher update cycle", latestDiscoveredPeriod: null, latestResourceId: null, resourceUrl: null, resourceHashOrChecksum: null, schemaVersion: null, schemaFingerprint: null, firstSeenAt: reviewDate, lastCheckedAt: reviewDate, lastSuccessfullyIngestedAt: null, authorityRank: 1, status: "documented_adapter_pending", knownCaveats: Object.freeze(["Ownership is limited to information supplied to Primary Care Services.", "The restricted All Wales Pharmacy Database is not integrated."]), provenanceNotes: "The public page stated information was correct on 1 May 2026 at review." }),
  Object.freeze({
    sourceId: "nwssp.practice-pharmacy-flow", publisher: "NHS Wales Shared Services Partnership", datasetName: "Pharmacy / Practice Dispensing Data", datasetSlugOrIdentifier: "pharmacy-practice-dispensing-data", jurisdiction: "Wales", coverage: "Practice-to-pharmacy and pharmacy-to-practice item flows in Wales", purpose: "Wales dispensing flow and pharmacy activity.", accessMethod: "file_download", apiOrDownload: "https://nwssp.nhs.wales/ourservices/primary-care-services/general-information/data-and-publications/pharmacy-practice-dispensing-data/", baseEndpointOrDiscoveryMethod: "Publisher page and monthly workbook", licence: "NHS Wales publication terms", publicationFrequency: "Monthly", typicalReportingLag: "Publisher update cycle", latestDiscoveredPeriod: null, latestResourceId: null, resourceUrl: null, resourceHashOrChecksum: null, schemaVersion: null, schemaFingerprint: null, firstSeenAt: reviewDate, lastCheckedAt: reviewDate, lastSuccessfullyIngestedAt: null, authorityRank: 1, status: "documented_adapter_pending", knownCaveats: Object.freeze(["Workbooks contain four logical sheets and retain only the current and two complete financial years."]), provenanceNotes: "The public page documents contractor addresses, practice addresses and both flow directions." }),
  Object.freeze({
    sourceId: "bso.dispensing-contractor", publisher: "Business Services Organisation Northern Ireland", datasetName: "Dispensing by Contractor", datasetSlugOrIdentifier: "dispensing-by-contractor", jurisdiction: "Northern Ireland", coverage: "Northern Ireland GP-practice to dispensing-contractor paid items", purpose: "Northern Ireland dispensing flows and contractor activity.", accessMethod: "ckan_action_api", apiOrDownload: "https://admin.opendatani.gov.uk/api/3/action", baseEndpointOrDiscoveryMethod: "package_show for dispensing-by-contractor", licence: "Open Government Licence v3.0", publicationFrequency: "Monthly", typicalReportingLag: "Approximately two months", latestDiscoveredPeriod: null, latestResourceId: null, resourceUrl: null, resourceHashOrChecksum: null, schemaVersion: null, schemaFingerprint: null, firstSeenAt: reviewDate, lastCheckedAt: null, lastSuccessfullyIngestedAt: null, authorityRank: 1, status: "discovery_implemented", knownCaveats: Object.freeze(["Paid claims are not NovaPharm sales.", "No patient-level data is required or permitted."]), provenanceNotes: "Official OpenDataNI dataset published by BSO." }),
  Object.freeze({
    sourceId: "gphc.premises", publisher: "General Pharmaceutical Council", datasetName: "Registered pharmacy premises", datasetSlugOrIdentifier: "gphc-data-subscription", jurisdiction: "United Kingdom", coverage: "Registered premises in England, Scotland and Wales", purpose: "Regulator-level premises identity and status cross-check.", accessMethod: "licensed_subscription", apiOrDownload: "https://www.pharmacyregulation.org/about-us/what-we-do/data-subscription-service", baseEndpointOrDiscoveryMethod: "GPhC subscription service", licence: "Paid annual GPhC data subscription licence", publicationFrequency: "Daily extracts; weekly changes", typicalReportingLag: "Publisher update cycle", latestDiscoveredPeriod: null, latestResourceId: null, resourceUrl: null, resourceHashOrChecksum: null, schemaVersion: null, schemaFingerprint: null, firstSeenAt: reviewDate, lastCheckedAt: reviewDate, lastSuccessfullyIngestedAt: null, authorityRank: 1, status: "licence_required", knownCaveats: Object.freeze(["No subscription credentials or reuse licence are present.", "The public search register is not permission to scrape or bulk reuse."]), provenanceNotes: "Integration remains blocked until the owner obtains and approves the subscription licence." }),
  Object.freeze({
    sourceId: "psni.premises", publisher: "Pharmaceutical Society of Northern Ireland", datasetName: "Registered pharmacy premises", datasetSlugOrIdentifier: "psni-live-and-monthly-register", jurisdiction: "Northern Ireland", coverage: "Registered premises in Northern Ireland", purpose: "Regulator-level premises identity and status cross-check.", accessMethod: "file_download", apiOrDownload: "https://psni.org.uk/pharmacies-monthly-premises-register-upload/", baseEndpointOrDiscoveryMethod: "Monthly list plus live public register", licence: "PSNI website terms", publicationFrequency: "Monthly snapshot with live register cross-check", typicalReportingLag: "Publisher update cycle", latestDiscoveredPeriod: null, latestResourceId: null, resourceUrl: null, resourceHashOrChecksum: null, schemaVersion: null, schemaFingerprint: null, firstSeenAt: reviewDate, lastCheckedAt: reviewDate, lastSuccessfullyIngestedAt: null, authorityRank: 1, status: "documented_adapter_pending", knownCaveats: Object.freeze(["Monthly list is a snapshot and does not replace the live register."]), provenanceNotes: "Premises identifiers must not be inferred from name or postcode alone." }),
] satisfies readonly SourceRegistryEntry[]);

export function registryEntry(sourceId: string): SourceRegistryEntry {
  const entry = sourceRegistry.find((candidate) => candidate.sourceId === sourceId);
  if (!entry) throw new Error(`Unknown medicines intelligence source: ${sourceId}`);
  return entry;
}

export function applyCkanDiscovery(
  entry: SourceRegistryEntry,
  dataset: CkanPackage,
  checkedAt: string,
): SourceRegistryEntry {
  const resources = discoverResources(dataset.resources);
  const latest: DiscoveredResource | undefined = resources.at(-1);
  if (!latest) {
    return Object.freeze({ ...entry, lastCheckedAt: checkedAt, status: "source_review_required", knownCaveats: Object.freeze([...entry.knownCaveats, "No period-bearing active CSV or ZIP resource was discovered."]) });
  }
  return Object.freeze({
    ...entry,
    datasetSlugOrIdentifier: dataset.name,
    licence: dataset.license_id || entry.licence,
    latestDiscoveredPeriod: latest.period.key,
    latestExpectedPeriod: latest.period.key,
    latestResourceId: latest.resource.id,
    resourceUrl: latest.resource.url,
    resourceHashOrChecksum: latest.resource.sha256 || latest.resource.hash || null,
    schemaFingerprint: latest.fingerprint,
    lastCheckedAt: checkedAt,
    status: "discovery_implemented",
  });
}
