import assert from "node:assert/strict";
import test from "node:test";
import { forecastMonthlySeries, reconcileBottomUp, type TimeSeriesPoint } from "../src/index.ts";

function series(months = 36, offset = 0): readonly TimeSeriesPoint[] {
  return Array.from({ length: months }, (_, index) => {
    const date = new Date(Date.UTC(2023, index, 1));
    return Object.freeze({ period: `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, "0")}`, value: 100 + offset + index * 1.5 + [0, 4, 8, 12, 8, 4, 0, -2, 0, 3, 7, 10][index % 12]! });
  });
}

test("forecasting selects a numerical baseline through rolling backtests", () => {
  const result = forecastMonthlySeries(series(), { horizon: 12 });
  assert.ok(["seasonal_naive", "holt_linear"].includes(result.model));
  assert.equal(result.values.length, 12);
  assert.equal(result.trainingCutoff, "2025-12");
  assert.equal(result.featureCutoff, "2025-12");
  assert.ok(result.backtest.observations > 0);
  assert.ok(result.backtest.wape >= 0);
  for (const point of result.values) {
    assert.ok(point.lower <= point.value);
    assert.ok(point.upper >= point.value);
  }
  assert.match(result.limitations[0] ?? "", /not generated by an LLM/iu);
});

test("forecasting rejects temporal leakage and false-precision horizons", () => {
  assert.throws(() => forecastMonthlySeries(series(), { horizon: 25 }));
  assert.throws(() => forecastMonthlySeries(series(), { horizon: 3, featureCutoff: "2026-01" }));
});

test("sparse histories use a deterministic fallback rather than fake seasonality", () => {
  const result = forecastMonthlySeries(series(8), { horizon: 3, seasonLength: 12 });
  assert.equal(result.model, "holt_linear");
});

test("bottom-up reconciliation keeps parent forecasts coherent", () => {
  const north = forecastMonthlySeries(series(24, 0), { horizon: 3 }).values;
  const south = forecastMonthlySeries(series(24, 40), { horizon: 3 }).values;
  const total = reconcileBottomUp({ north, south });
  assert.equal(total.length, 3);
  assert.equal(total[0]?.value, (north[0]?.value ?? 0) + (south[0]?.value ?? 0));
});
