using '../main.bicep'

param environmentCode = 'stg'
param location = readEnvironmentVariable('AZURE_LOCATION', 'uksouth')
param namePrefix = 'novapharm'
param publicOrigin = readEnvironmentVariable('NOVAPHARM_STAGING_ORIGIN', '')
param keyVaultBootstrapIpCidr = readEnvironmentVariable('AZURE_KEY_VAULT_BOOTSTRAP_IP_CIDR', '')
param enableBootstrapAdmin = bool(readEnvironmentVariable('NOVAPHARM_ENABLE_BOOTSTRAP_ADMIN', 'false'))
param sqlEntraAdminObjectId = readEnvironmentVariable('AZURE_SQL_ENTRA_ADMIN_OBJECT_ID')
param sqlEntraAdminLogin = readEnvironmentVariable('AZURE_SQL_ENTRA_ADMIN_LOGIN')
param sqlAutoPauseDelay = 60
param deployCandidateSlot = false
param enableEntraAuthentication = bool(readEnvironmentVariable('NOVAPHARM_ENABLE_ENTRA_AUTH', 'false'))
param entraTenantId = readEnvironmentVariable('AZURE_TENANT_ID')
param entraClientId = readEnvironmentVariable('NOVAPHARM_ENTRA_CLIENT_ID', '')
param entraExternalTenantId = readEnvironmentVariable('NOVAPHARM_ENTRA_EXTERNAL_TENANT_ID', '')
param entraAdminGroupId = readEnvironmentVariable('NOVAPHARM_ENTRA_ADMIN_GROUP_ID', '')
param entraBoardGroupId = readEnvironmentVariable('NOVAPHARM_ENTRA_BOARD_GROUP_ID', '')
param entraEmployeeGroupId = readEnvironmentVariable('NOVAPHARM_ENTRA_EMPLOYEE_GROUP_ID', '')
param entraCustomerGroupId = readEnvironmentVariable('NOVAPHARM_ENTRA_CUSTOMER_GROUP_ID', '')
param enableDefenderForStorage = bool(readEnvironmentVariable('NOVAPHARM_ENABLE_DEFENDER_FOR_STORAGE', 'false'))
param sharePointHostname = readEnvironmentVariable('NOVAPHARM_SHAREPOINT_HOSTNAME', '')
param sharePointSitePath = readEnvironmentVariable('NOVAPHARM_SHAREPOINT_SITE_PATH', '')
param sharePointDriveId = readEnvironmentVariable('NOVAPHARM_SHAREPOINT_DRIVE_ID', '')
param sharePointExecutivePlatformPath = readEnvironmentVariable('NOVAPHARM_SHAREPOINT_EXECUTIVE_PLATFORM_PATH', '')
param operationsEmail = readEnvironmentVariable('NOVAPHARM_OPERATIONS_EMAIL', '')
param emailFrom = readEnvironmentVariable('NOVAPHARM_EMAIL_FROM', '')
param contactNotificationTo = readEnvironmentVariable('NOVAPHARM_CONTACT_NOTIFICATION_TO', '')
param emailProvider = readEnvironmentVariable('NOVAPHARM_EMAIL_PROVIDER', 'auto')
param microsoftEmailSender = readEnvironmentVariable('NOVAPHARM_MICROSOFT_EMAIL_SENDER', '')
